
CREATE TABLE dbo_borrow( --全量同步
CREATE TABLE dbo_borrow_dadd( --增量同步
id bigint,
loaner_id bigint,
post_id bigint,
post_time varchar(50),
name varchar(400),
logo varchar(100),
category varchar(50),
status int,
full_time varchar(50),
amount numeric(19, 2),
interest_total numeric(19, 2),
rate numeric(19, 4),
is_display boolean,
invest_process int,
repay_process int,
is_be_overdue boolean,
cycle_type int,
cycle int,
repay_type int,
fund_cycle_type int,
fund_cycle int,
deadline varchar(50),
is_reward boolean,
reward_rate numeric(19, 4),
loaner_fee_total numeric(19, 4),
interest_fee_total numeric(19, 4),
loaner_cost_id bigint,
ip varchar(100),
auditing_member_id bigint,
auditing_remark varchar(1000),
description varchar(8000),
issues int,
portal_weight int,
issued int,
date_created varchar(50),
last_updated varchar(50),
created_by bigint,
updated_by bigint,
version bigint,
last_payment date,
is_vip boolean,
fund_deadline varchar(50),
last_check_fail_date varchar(50),
last_check_success_date varchar(50),
check_result_status boolean,
next_repay_time varchar(50),
min_invest_day int,
interest_type int,
is_settlement boolean,
trade_out numeric(19, 2),
surplus numeric(19, 2),
is_pause boolean,
need_settlement_date varchar(50),
loaner_total numeric(19, 2),
trade_in numeric(19, 2),
invest_max numeric(19, 2),
invest_min numeric(19, 2),
settlement_date varchar(50),
keyword varchar(500),
is_be_overdueing boolean,
run_off_date varchar(50),
receipt_id bigint,
assure_type int,
assure_description varchar(256),
assure_company varchar(128),
category_type varchar(128),
contract varchar(32),
description_for_seo varchar(255),
pt varchar(20)
)

