
CREATE TABLE dbo_member( --全量同步
CREATE TABLE dbo_member_dadd( --增量同步
id bigint,
username varchar(200),
password varchar(200),
out_password varchar(200),
status int,
reg_time varchar(50),
last_login_time varchar(50),
reg_ip varchar(100),
real_name varchar(200),
email varchar(100),
is_valid_email boolean,
mobile varchar(100),
is_valid_mobile boolean,
idcard varchar(100),
is_valid_idcard boolean,
recommend_id bigint,
credit_point int,
credit_reason varchar(500),
credit_limit int,
freeze_credit_limit int,
is_transfer boolean,
is_vip boolean,
is_recharge boolean,
is_withdraw boolean,
is_admin boolean,
date_created varchar(50),
last_updated varchar(50),
created_by bigint,
updated_by bigint,
version bigint,
is_deleted boolean,
enabled boolean,
account_expired boolean,
account_locked boolean,
password_expired boolean,
reg_address varchar(255),
remark varchar(255),
avatar varchar(255),
is_old boolean,
is_company boolean,
auth_reason varchar(255),
vip_end_date varchar(50),
reg_referer varchar(1000),
uname varchar(200),
identity_change varchar(100),
reg_way varchar(100),
pt varchar(20)
)
    
