CREATE TABLE account_recharge(
-- CREATE TABLE dbo_account_recharge(
-- CREATE TABLE dbo_account_recharge_dadd(
id bigint,
member_id bigint,
account_id bigint,
cost_id bigint,
charge_type int,
cash numeric(19, 2),
prize_cash numeric(19, 2),
fee numeric(19, 2),
charge_status int,
explain varchar(2000),
pay_tran_no varchar(100),
bank_name varchar(200),
bank_account varchar(100),
bank_city_id bigint,
charge_way varchar(50),
ip varchar(50),
is_manual boolean,
reason varchar(2000),
date_created varchar(50),
last_updated varchar(50),
created_by bigint,
updated_by bigint,
version bigint,
gopay_tran_date_time varchar(255),
handle_time varchar(50),
handler_id bigint,
bank_city varchar(50),
order_no varchar(255),
check_original_result varchar(255),
check_status int,
check_date varchar(50),
check_result varchar(1000),
check_by_admin_remark varchar(255),
check_by_admin_fix_status boolean,
pt varchar(20)
)
;

