CREATE TABLE member_info(
-- CREATE TABLE dbo_member_info(
-- CREATE TABLE dbo_member_info_dadd(
id bigint,
member_id bigint,
birthday varchar(50),
gender varchar(100),
age int,
hight_degree varchar(100),
school varchar(100),
edu_start_date varchar(50),
marriage varchar(100),
has_children boolean,
has_house boolean,
has_mortgage boolean,
has_car boolean,
has_car_loan boolean,
birth_place_id bigint,
current_address text,
resident_city_id bigint,
resident_telephone text,
person_image varchar(100),
date_created varchar(50),
last_updated varchar(50),
created_by bigint,
updated_by bigint,
version bigint,
qq_num  varchar(30),
occupation varchar(100),
hobby varchar(100),
postcode varchar(100),
modified_address text,
label_type varchar(100),
describe varchar(400),
has_contact boolean,
loan_type varchar(100),
pt varchar(20)
)
;
